version: '3.9'
services:
  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - '9324-9325:9324-9325'
    volumes:
      - ./custom.conf:/opt/elasticmq.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9324"]
      interval: 30s
      timeout: 10s
      retries: 5