version: '3.9'
services:
  worker-orders:
    container_name: worker-orders
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - SQS_ENDPOINT=http://elasticmq:9324
      - REGION=us-west-2
    ports:
      - '3003:3003'
    volumes:
      - .:/src
      - /src/node_modules
    build:
      context: .
    command: npm run dev
  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - '9324:9324'
